version: "3.3"
services:
  redis:
    image: redis
    volumes:
      - ./storage/redis-data:/data
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - ./storage/mongo-data:/data/db
    ports:
      - "27017:27017"